name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x
          - 14.x
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: 'Install Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - name: 'Unit Tests with Node.js ${{ matrix.node-version }}'
        run: |
          rm package-lock.json
          npm install
          npm test
  code-coverage:
    name: Coveralls Code Coverage
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: 'Test Coverage with Node.js 12.x'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          rm package-lock.json
          npm install
          npm run test:coverage
      - name: Push to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
